/**
 * Home Assistant Integration for WebUntis
 * This file contains Home Assistant-specific functionality for automation and notifications
 * 
 * Features:
 * - Send homework notifications to Home Assistant
 * - Call Home Assistant REST API services
 * - Integration with Home Assistant notification services
 */

// ==========================================
// HOME ASSISTANT INTEGRATION FUNCTIONS
// ==========================================

/**
 * Send homework data to Home Assistant as a notification
 * 
 * @param {Object} config - WebUntis configuration object
 * @param {Object} haConfig - Home Assistant configuration
 * @param {number} days - Number of days to look ahead (default: 3)
 * @param {Object} options - Additional options for notification
 * @param {string} options.title - Custom notification title
 * @param {boolean} options.includeDetails - Include detailed homework information
 * @param {string} options.service - Override default notification service
 * @returns {Promise<Object>} Result object with success status
 */
async function sendHomeworkToHomeAssistant(config, haConfig, days = 3, options = {}) {
    if (!config) {
        throw new Error('WebUntis config parameter is required');
    }
    
    if (!haConfig || !haConfig.url || !haConfig.token) {
        throw new Error('Home Assistant config with URL and token is required');
    }

    try {
        // Get API instance using the global function from WebUntis.js
        const api = await getWebUntisApiInstance(config);
        const homeworkList = await api.getHomeworkList(days, true); // Next n days, open only
        
        // Filter out homework due today
        let filteredHomeworkList = null;
        if (homeworkList) {
            const today = new Date();
            const todayStr = parseInt(WebUntisAPI.formatDate(today)); // Convert to YYYYMMDD format
            
            filteredHomeworkList = homeworkList.filter(hw => hw.dueDate !== todayStr);
        }
        
        // Only send notification if homework exists after filtering
        if (filteredHomeworkList && filteredHomeworkList.length > 0) {
            // Format homework for notification
            let message;
            if (options.includeDetails) {
                message = api.formatHomework(filteredHomeworkList, days, true);
            } else {
                // Create summary message
                message = `📚 ${filteredHomeworkList.length} homework assignment(s) due in the next ${days} days (excluding today):\n\n`;
                filteredHomeworkList.forEach((hw, index) => {
                    const dueDate = api.formatWebUntisDate(hw.dueDate);
                    const subject = hw.subjectName || 'Unknown Subject';
                    message += `${index + 1}. ${subject} - Due: ${dueDate}\n`;
                });
                message += '\n🤖 Generated by WebUntis API';
            }
            
            // Prepare notification data
            const notificationData = {
                message: message,
                title: options.title || '📚 Upcoming Homework Reminder',
                data: {
                    tag: 'webuntis_homework',
                    group: 'webuntis',
                    importance: 'high',
                    homework_count: filteredHomeworkList.length,
                    days_ahead: days
                }
            };
            
            // Send notification to Home Assistant
            const service = options.service || haConfig.service || 'notify.mobile_app';
            const result = await callHomeAssistantAPI(haConfig, service, notificationData);
            
            if (result.success) {
                console.log(`📱 Home Assistant notification sent successfully!`);
                console.log(`📚 Found ${filteredHomeworkList.length} homework assignments (filtered out today's homework)`);
                return {
                    success: true,
                    homeworkCount: filteredHomeworkList.length,
                    message: 'Notification sent successfully',
                    data: result.data
                };
            } else {
                console.error('❌ Failed to send Home Assistant notification:', result.error);
                return {
                    success: false,
                    error: result.error
                };
            }
        } else {
            console.log(`😎 No homework found for the next ${days} days (excluding today) - notification not sent`);
            return {
                success: true,
                homeworkCount: 0,
                message: 'No homework found - notification not sent'
            };
        }
        
    } catch (error) {
        console.error('❌ Error sending homework to Home Assistant:', error.toString());
        return {
            success: false,
            error: error.toString()
        };
    }
}
/**
 * Call Home Assistant REST API to execute services
 * 
 * @param {Object} haConfig - Home Assistant configuration
 * @param {string} service - Service to call (e.g., 'notify.mobile_app', 'telegram_bot.send_message')
 * @param {Object} serviceData - Data to send to the service
 * @returns {Promise<Object>} Result object with success status and response data
 */
async function callHomeAssistantAPI(haConfig, service, serviceData) {
    if (!haConfig || !haConfig.url || !haConfig.token) {
        throw new Error('Home Assistant config with URL and token is required');
    }
    
    if (!service) {
        throw new Error('Service parameter is required');
    }

    try {
        // Parse service to get domain and service name
        const serviceParts = service.split('.');
        if (serviceParts.length !== 2) {
            throw new Error('Service must be in format "domain.service" (e.g., "notify.mobile_app")');
        }
        
        const [domain, serviceName] = serviceParts;
        const url = `${haConfig.url.replace(/\/$/, '')}/api/services/${domain}/${serviceName}`;
        
        const headers = {
            'Authorization': `Bearer ${haConfig.token}`,
            'Content-Type': 'application/json',
            'User-Agent': 'WebUntisAPI/1.0'
        };
        
        const requestBody = JSON.stringify(serviceData);
        
        let response;
        
        // Check if we're in Google Apps Script environment
        if (typeof UrlFetchApp !== 'undefined') {
            // Google Apps Script environment
            const gasOptions = {
                method: 'POST',
                headers: headers,
                payload: requestBody,
                muteHttpExceptions: true
            };
            
            const gasResponse = UrlFetchApp.fetch(url, gasOptions);
            response = {
                ok: gasResponse.getResponseCode() >= 200 && gasResponse.getResponseCode() < 300,
                status: gasResponse.getResponseCode(),
                text: () => Promise.resolve(gasResponse.getContentText()),
                json: () => Promise.resolve(JSON.parse(gasResponse.getContentText()))
            };
        } else {
            // Node.js environment
            const fetch = require('node-fetch') || global.fetch;
            if (!fetch) {
                throw new Error('fetch is not available. Install node-fetch: npm install node-fetch');
            }
            
            response = await fetch(url, {
                method: 'POST',
                headers: headers,
                body: requestBody
            });
        }
        
        if (response.ok) {
            const responseData = await response.json();
            console.log(`✅ Home Assistant API call successful: ${service}`);
            return {
                success: true,
                data: responseData,
                status: response.status
            };
        } else {
            const errorText = await response.text();
            console.error(`❌ Home Assistant API call failed: ${response.status} - ${errorText}`);
            return {
                success: false,
                error: `HTTP ${response.status}: ${errorText}`,
                status: response.status
            };
        }
        
    } catch (error) {
        console.error('❌ Error calling Home Assistant API:', error.toString());
        return {
            success: false,
            error: error.toString()
        };
    }
}

/**
 * Create a Home Assistant automation helper
 * This function helps create sensor data for Home Assistant to track homework status
 * 
 * @param {Object} config - WebUntis configuration object
 * @param {Object} haConfig - Home Assistant configuration
 * @param {number} days - Number of days to look ahead (default: 7)
 * @returns {Promise<Object>} Sensor data for Home Assistant
 */
async function createHomeworkSensorData(config, haConfig, days = 7) {
    if (!config) {
        throw new Error('WebUntis config parameter is required');
    }

    try {
        const api = await getWebUntisApiInstance(config);
        const homeworkList = await api.getHomeworkList(days, true);
        
        // Filter out homework due today
        let filteredHomeworkList = null;
        if (homeworkList) {
            const today = new Date();
            const todayStr = parseInt(WebUntisAPI.formatDate(today));
            
            filteredHomeworkList = homeworkList.filter(hw => hw.dueDate !== todayStr);
        }
        
        const now = new Date();
        const sensorData = {
            state: filteredHomeworkList ? filteredHomeworkList.length : 0,
            attributes: {
                unit_of_measurement: 'assignments',
                friendly_name: 'WebUntis Homework Count',
                icon: 'mdi:book-open-page-variant',
                last_updated: now.toISOString(),
                days_ahead: days,
                homework_list: filteredHomeworkList ? filteredHomeworkList.map(hw => ({
                    subject: hw.subjectName || 'Unknown Subject',
                    due_date: api.formatWebUntisDate(hw.dueDate),
                    text: hw.text || 'No description',
                    lesson_id: hw.lessonId
                })) : [],
                next_due_date: filteredHomeworkList && filteredHomeworkList.length > 0 
                    ? api.formatWebUntisDate(filteredHomeworkList[0].dueDate) 
                    : null
            }
        };
        
        console.log(`📊 Created sensor data: ${sensorData.state} homework assignments`);
        return {
            success: true,
            sensorData: sensorData,
            homeworkCount: sensorData.state
        };
        
    } catch (error) {
        console.error('❌ Error creating homework sensor data:', error.toString());
        return {
            success: false,
            error: error.toString(),
            sensorData: {
                state: 'unavailable',
                attributes: {
                    friendly_name: 'WebUntis Homework Count',
                    icon: 'mdi:book-open-page-variant',
                    last_updated: new Date().toISOString(),
                    error: error.toString()
                }
            }
        };
    }
}

/**
 * Update a Home Assistant sensor with homework data
 * This function updates a sensor entity in Home Assistant with current homework status
 * 
 * @param {Object} config - WebUntis configuration object
 * @param {Object} haConfig - Home Assistant configuration
 * @param {string} entityId - The entity ID of the sensor to update (e.g., 'sensor.webuntis_homework')
 * @param {number} days - Number of days to look ahead (default: 7)
 * @returns {Promise<Object>} Result object with success status
 */
async function updateHomeworkSensor(config, haConfig, entityId, days = 7) {
    if (!entityId) {
        throw new Error('Entity ID is required');
    }
    
    try {
        const sensorResult = await createHomeworkSensorData(config, haConfig, days);
        
        if (!sensorResult.success) {
            return sensorResult;
        }
        
        // Update the sensor using Home Assistant's REST API
        const url = `${haConfig.url.replace(/\/$/, '')}/api/states/${entityId}`;
        
        const headers = {
            'Authorization': `Bearer ${haConfig.token}`,
            'Content-Type': 'application/json',
            'User-Agent': 'WebUntisAPI/1.0'
        };
        
        const requestBody = JSON.stringify(sensorResult.sensorData);
        
        let response;
        
        // Check if we're in Google Apps Script environment
        if (typeof UrlFetchApp !== 'undefined') {
            // Google Apps Script environment
            const gasOptions = {
                method: 'POST',
                headers: headers,
                payload: requestBody,
                muteHttpExceptions: true
            };
            
            const gasResponse = UrlFetchApp.fetch(url, gasOptions);
            response = {
                ok: gasResponse.getResponseCode() >= 200 && gasResponse.getResponseCode() < 300,
                status: gasResponse.getResponseCode(),
                text: () => Promise.resolve(gasResponse.getContentText())
            };
        } else {
            // Node.js environment
            const fetch = require('node-fetch') || global.fetch;
            if (!fetch) {
                throw new Error('fetch is not available. Install node-fetch: npm install node-fetch');
            }
            
            response = await fetch(url, {
                method: 'POST',
                headers: headers,
                body: requestBody
            });
        }
        
        if (response.ok) {
            console.log(`✅ Home Assistant sensor updated: ${entityId} = ${sensorResult.sensorData.state}`);
            return {
                success: true,
                entityId: entityId,
                homeworkCount: sensorResult.sensorData.state,
                message: 'Sensor updated successfully'
            };
        } else {
            const errorText = await response.text();
            console.error(`❌ Failed to update Home Assistant sensor: ${response.status} - ${errorText}`);
            return {
                success: false,
                error: `HTTP ${response.status}: ${errorText}`,
                status: response.status
            };
        }
        
    } catch (error) {
        console.error('❌ Error updating Home Assistant sensor:', error.toString());
        return {
            success: false,
            error: error.toString()
        };
    }
}

// Export functions for Node.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        sendHomeworkToHomeAssistant,
        callHomeAssistantAPI,
        createHomeworkSensorData,
        updateHomeworkSensor
    };
}